#!/bin/bash
# Runs after the full message is assembled (including --trailer flags).
sed -i '' '/cursoragent@cursor\.com/d' "$1"
sed -i '' '/^[Cc]o-authored-by:.*[Cc]ursor/d' "$1"
sed -i '' '/^[Mm]ade-with:.*[Cc]ursor/d' "$1"
