#!/bin/bash
# Remove Cursor attribution injected into commit messages.
sed -i '' '/cursoragent@cursor\.com/d' "$1"
sed -i '' '/^[Cc]o-authored-by:.*[Cc]ursor/d' "$1"
sed -i '' '/^[Mm]ade-with:.*[Cc]ursor/d' "$1"
